### ISSUE TITLE
Ganache-cli outputs cli.node.js contents when running commands in docker image

### ISSUE THREAD

**Issue by karneaud** [ConsenSys-archive/ganache-cli-archive#504]
Trying to run ganache testrpc service in docker container using installed npm package and in running command ` ganache-cli --account=0x627142118b4a998f24db31ff38ab5e8f49299e63,1234567890123456789123456789 --account=0xc0ce36fc004bf4ea51d9a30bb8737c7012ec5d1f,1234567890123456789123456789` the command outputs file contents and docker container exits

## Expected Behavior

Should execute the command successfully 

## Current Behavior

Outputs file contents of **usr/local/share/.config/yarn/global/node_modules/ganache-cli/build/cli.node.js:2** 

docker container exits with error code 1

## Steps to Reproduce (for bugs)

1. build docker image 
```
FROM arm32v7/node:9-stretch

RUN yarn global add ganache-cli

EXPOSE 8545
ENTRYPOINT ["ganache-cli"]
```
2.  run service
```
testrpc: # A very simple/light geth, only for testing purpose
    container_name: testrpc
    build: testrpc
    ports:
      - "8545:8545"
    command: '--debug --account="0x627142118b4a998f24db31ff38ab5e8f49299e63,1234567890123456789123456789" --account="0xc0ce36fc004bf4ea51d9a30bb8737c7012ec5d1f,1234567890123456789123456789"'
```

## Context

I'm trying to learn and develop Dapps using ETH Solidity with Truffle/ Geth/ Ganache

got this on installing via npm 

>

>  warning ganache-cli > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
> warning ganache-cli > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
> warning ganache-cli > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
> warning ganache-cli > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> warning "ganache-cli > webpack-cli@2.0.14" has unmet peer dependency "webpack@^4.0.0".
> [4/4] Building fresh packages...
> success Installed "ganache-cli@6.1.0" with binaries:
> 

## Your Environment
* Version used: 6.1.0
* Version of Truffle/Remix/Other tools used: Docker, Docker Compose
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [x ] 9.x
* Yarn 1.5.1
* Operating System and version (include distro if Linux): Docker 18.03.0-ce on linux, arm32v7/node:9-stretch
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]
