### ISSUE TITLE
Default account balances are set to 0 after a while

### ISSUE THREAD

**Issue by zatsepinvl** [ConsenSys-archive/ganache-cli-archive#512]
Using ganache-cli via docker (https://hub.docker.com/r/trufflesuite/ganache-cli/) with latest tag and MetaMask 4.2.0 in Firefox Developer Edition **from different machines simultaneously**, all default account balances are set to 0 after a while (checked by command `web3.eth.getBalance(web3.eth.accounts[0]).toNumber()` through truffle console).

docker-compose to start ganache:
```
version: "3"

networks:
  my-network:

services:
  ganache:
    image: trufflesuite/ganache-cli
    restart: always
    container_name: my_ganache
    ports:
      - 8545:8545
    command: -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" -i 4448
    networks:
      - my-network

```

The same behavior was discovered for https://github.com/harshjv/docker-testrpc
