### ISSUE TITLE
Unable to reach ganache-cli in a docker container from docker compose

### ISSUE THREAD

**Issue by SalahAdDin** [ConsenSys-archive/ganache-cli-archive#780]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [X]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5f47a4035580fa092b2896e0

## Expected Behavior

Both _memento_ and _explorer_ must be connected to _ganache-cli_.

## Current Behavior
 For Memento(docker logs):
```shell
time="2020-08-27T12:24:40Z" level=info msg="[eth] starting best block tracker"
time="2020-08-27T12:24:40Z" level=info msg="[eth] setting up websocket connection"
time="2020-08-27T12:24:41Z" level=warning msg="error connecting to server: dial tcp 127.0.0.1:8546: connect: connection refused "
```

For Explorer(in-browser console):
 ```
App.ts:25 Couldn't load application config SyntaxError: Unexpected token / in JSON at position 84
    at JSON.parse (<anonymous>)
    at _i.<anonymous> (HttpRequest.ts:101)
    at Generator.next (<anonymous>)
    at a (HttpRequestError.ts:2)
```
It means they cannot connect properly to  _ganache-cli_.

## Steps to Reproduce (for bugs)

1. Launch up the network: `docker-compose -f docker-compose-explorer.yml up`
2. Review the _docker-compose_ logs to see the _memento_ container logs(you can use Kitematic).
3. Go to the localhost in browser and check the developer console.

## Context
This is my _docker compose_ file:
```yaml
version: "3.7"
services:
  redis:
    container_name: memento-redis
    image: redis:5.0.5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - .volumes/redis:/data
  postgres:
    container_name: memento-postgres
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=memento
      - POSTGRES_DB=memento
      - POSTGRES_PASSWORD=password
    volumes:
      - .volumes/postgresql:/var/lib/postgresql/data
  ganache-cli:
    image: trufflesuite/ganache-cli
    container_name: ganache-cli
    ports:
      - 8545:8545
      - 8546:8546
  memento:
    container_name: memento
    image: alethio/memento:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 127.0.0.1:3001:3001
      - 127.0.0.1:3000:3000
    environment:
      - PG_PASSWORD=password
    volumes:
      - .volumes/memento:/config
  explorer:
    container_name: memento-lite-explorer
    image: alethio/ethereum-lite-explorer:latest
    restart: always
    depends_on:
      - memento
      - ganache-cli
    ports:
      - 127.0.0.1:80:80
    environment:
      - APP_NODE_URL="http://127.0.0.1:8545"
    volumes:
      - .volumes/lite-explorer/config.json:/usr/share/nginx/html/config.json
```
Also, i opened an [issue](https://github.com/Alethio/memento/issues/18https://github.com/Alethio/memento/issues/18) in _memento_ repository and i found the next [issue](https://github.com/trufflesuite/ganache-cli/issues/556).

## Your Environment
* Version used:v6.10.1 (ganache-core: 2.11.2)
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux):

**Comment by mikeseese** [comment]
it seems that I can't reproduce this as there is missing configuration. What do your various config files look like (i.e. `.volumes/memento`, `.volumes/lite-explorer/config.json`, etc)? make sure to sensor out any sensitive information

**Comment by SalahAdDin** [comment]
I have this in _memento_ configuration file:
```yaml
# api-related fields
api:
  # The port on which the API will be exposed (default:3001)
  port: 3001

  # Enable/disable development CORS
  dev-cors: true

  # Allowed hosts for HTTP API development CORS
  dev-cors-host: "*"

# Dashboard-related fields
dashboard:
  # The port on which the Dashboard will be exposed (default:3000)
  # WARNING: it must not be the same as api.port!
  port: 3000

  config-management:
    enabled: true

# database fields
db:
  # Database host
  host: "memento-postgres"

  # Database port
  port: 5432

  # Database sslmode
  sslmode: "disable"

  # Database name
  dbname: "memento"

  # Database user (also allowed via PG_USER env var)
  user: "memento"

# ethereum-related fields
eth:
  client:
    # HTTP endpoint of a web3-compatible node (mandatory)
    http: "http://127.0.0.1:8545"

    # Websockets endpoint of JSON-RPC enabled node (optional)
    # if this is present, the task manager will use a newHeads subscription to watch for new blocks
    # if not present, the task manager will use polling to get the highest block
    ws: "ws://127.0.0.1:8546"

    # The interval at which the task manager will poll the node for best block (default:"15s")
    # optional, only used if `ws` url is not specified
    poll-interval: "15s"

# feature flags
feature:
  # Backfilling
  backfill:
    # Enable/disable the backfilling feature
    enabled: false

  # Lag feature
  lag:
    # Enable/disable the lag feature
    enabled: true

    # The amount of blocks to lag behind the tip of the chain if the lag feature is enabled
    value: 10

  # Automatic migrations
  automigrate:
    # Enable/disable the automatic migrations
    enabled: true

  # Uncles scraping
  uncles:
    # Enable/disabled the uncles scraping
    enabled: false

# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

# redis-related fields
redis:
  # URL of redis server (default:"localhost:6379")
  server: "memento-redis:6379"

  # The name of the redis list the scraper will use for task management (default: "todo")
  list: "todo"

```
