### ISSUE TITLE
Error running -h "0.0.0.0"

### ISSUE THREAD

**Issue by rodoufu** [ConsenSys-archive/ganache-cli-archive#816]
I have created a dockerfile like that:
```Dockerfile
ARG NODE_VERSION=15.5.1-slim
FROM node:${NODE_VERSION} AS builder

RUN yarn global add truffle
RUN yarn global add ganache-cli
```

## Expected Behavior

I'm starting the image with a docker stack like that:

```yaml
version: '3.7'

services:
  ganache:
    image: 'my_image:latest'
    hostname: ganache
    deploy:
      restart_policy:
        condition: none
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: 5
    ports:
    - 8545:8545
    entrypoint:
      - 'ganache-cli'
      - '-m "mnemonic"'
      - '-h "0.0.0.0"'
      - '-p 8545'
```
When I try to access it:

```sh
$ curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' localhost:8545
```

I expect a response like this:

```js
{"id":67,"jsonrpc":"2.0","result":"EthereumJS TestRPC/v2.13.2/ethereum-js"}
```

## Current Behavior

But when I run it:

```sh
$ curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' localhost:8545
```

I'm getting it:
```sh
curl: (7) Failed to connect to localhost port 8545: Connection refused
```

## Possible Solution

When I check the logs in the container I get:

```sh
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
Error: getaddrinfo ENOTFOUND  "0.0.0.0"
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)
```

## Steps to Reproduce (for bugs)

1. Create the docker image
2. Start the docker stack
3. Try to access the ganache container

## Your Environment
* Version used: v6.12.2
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x, [x] 15.x
* Operating System and version (include distro if Linux): Ubuntu
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Can you try node 14 instead?

**Comment by rodoufu** [comment]
Same error with [node:14.15.4-slim](https://hub.docker.com/layers/node/library/node/14.15.4-slim/images/sha256-4ec1416247273c7318c0351e04ed997dd8c8059fc53c94e6c5a65773a299395f?context=explore) as base image.

Here is how my services are running:
```sh
$ docker service ls
ID                  NAME                 MODE                REPLICAS            IMAGE               PORTS
1m00avaeylck        mystack_ganache      replicated          1/1                 my_image:latest    *:8545->8545/tcp
```

**Comment by davidmurdoch** [comment]
I don't know docker very well, so I'm afraid I won't be of much help. You can read our docker config here: https://github.com/trufflesuite/ganache-cli/blob/develop/Dockerfile or try using our official Docker container: `docker run --publish 8545:8545 trufflesuite/ganache-cli:latest
` (https://hub.docker.com/r/trufflesuite/ganache-cli/)

**Comment by rodoufu** [comment]
> I don't know docker very well, so I'm afraid I won't be of much help. You can read our docker config here: https://github.com/trufflesuite/ganache-cli/blob/develop/Dockerfile or try using our official Docker container: `docker run --publish 8545:8545 trufflesuite/ganache-cli:latest ` (https://hub.docker.com/r/trufflesuite/ganache-cli/)

When I use it like that it does work, but the problem is when I run it as a service.

The reason I'm trying to do it like that is that I want to provide the mnemonic for it, is there a way I can provide it to your ganache-cli docker image? 
Something like an environment variable or sending parameters to the entry point of the image.

**Comment by davidmurdoch** [comment]
From https://github.com/trufflesuite/ganache-CLI#docker:

> To pass options to ganache-cli through Docker simply add the arguments to the run command:

```
docker run --detach --publish 8545:8545 trufflesuite/ganache-cli:latest --accounts 10 --debug
                                                                        ^^^^^^^^^^^^^^^^^^^^^
```

so for passing a mnemonic you would:

```
docker run --detach --publish 8545:8545 trufflesuite/ganache-cli:latest --mnemonic {YOUR-MNEMONIC-HERE}
```

Does this solve your issue?

**Comment by rodoufu** [comment]
I'm going to try that with your image and passing the arguments to the docker service in the docker stack and I get back here with the answer.

@davidmurdoch thanks for all your help so far, I hope it helps someone else in the future as well.

**Comment by rodoufu** [comment]
I've just figured out how to fix that problem, here follows the config:
```yaml
version: '3.7'

services:
  ganache:
    image: 'trufflesuite/ganache-cli:v6.12.2'
    hostname: ganache
    deploy:
      restart_policy:
        condition: none
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: 5
    ports:
    - 8545:8545
    command: '-m "mnemonic"'
```
